name: React Native Android CI (Dev)

on:
  push:
    branches:
      - main
      - dev
      - feature/* # for feature branches
      - fix/minor-issues

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies (ignore peer conflicts)
        run: npm ci --legacy-peer-deps || npm install --legacy-peer-deps --force

      - name: Give Gradlew permission
        run: chmod +x android/gradlew

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # üóùÔ∏è Decode keystore from GitHub secret
      - name: Decode Keystore
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > android/app/my-release-key.keystore

      - name: Build Android debug APK
        run: cd android && ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk

      # Set up JDK 17 to fix PKCS12 keystore issue
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17


      # üèóÔ∏è Build release APK
      - name: Build Android release APK
        run: cd android && ./gradlew assembleRelease
        env:
          MYAPP_UPLOAD_STORE_FILE: my-release-key.keystore
          MYAPP_UPLOAD_KEY_ALIAS: ${{ secrets.MYAPP_UPLOAD_KEY_ALIAS }}
          MYAPP_UPLOAD_STORE_PASSWORD: ${{ secrets.MYAPP_UPLOAD_STORE_PASSWORD }}
          MYAPP_UPLOAD_KEY_PASSWORD: ${{ secrets.MYAPP_UPLOAD_KEY_PASSWORD }}

      # üì¶ Upload release artifact
      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/app-release.apk
